### ISSUE TITLE
[2.0.0] Release Checklist

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/Automation#1]
# ⚡ Energy Blocks
## Aluminum Cable
- [x] Mechanics
- [ ] Recipes
- [x] States
- [x] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Battery 
- [x] GUI
- [x] Mechanics
- [ ] Recipes
- [x] States
- [x] Textures
- [x] Upgrades
- [ ] Wiki Integration
- [x] Wiki Page

## Cable Bridge
- [ ] GUI
- [ ] Mechanics
- [ ] Recipes
- [ ] States
- [ ] Textures
- [ ] Upgrades
- [ ] Wiki Integration
- [ ] Wiki Page

## Solar Panel
- [ ] GUI
- [ ] Mechanics
- [ ] Recipes
- [ ] States
- [ ] Textures
- [ ] Upgrades
- [ ] Wiki Integration
- [ ] Wiki Page

# 🔧 Device Blocks
## Breaker Panel
- [ ] GUI
- [ ] Mechanics
- [ ] Recipes
- [ ] States
- [ ] Textures
- [ ] Upgrades
- [ ] Wiki Integration
- [ ] Wiki Page

## Remote Item Teleporter (RIT)
- [ ] GUI
- [ ] Mechanics
- [ ] Recipes
- [ ] States
- [ ] Textures
- [ ] Upgrades
- [ ] Wiki Integration
- [ ] Wiki Page

# 🧱 Building Blocks
## Machine Block
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Aluminum Block
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Raw Aluminum Block
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

# 💎 Ore Blocks
## Aluminum Ore
- [ ] Generation
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

# ⚙Machine Blocks
## Auto Farm
- [ ] GUI
- [ ] Mechanics
- [ ] Recipes
- [ ] States
- [ ] Textures
- [ ] Upgrades
- [ ] Wiki Integration
- [ ] Wiki Page

# 🔨 Tools

## Machine Wrench
- [ ] Mechanics
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

# 🧵 Items
## Aluminum Ingot
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Raw Aluminum
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Wooden Upgrade
- [ ] Animation Credits [Shadowdragon](https://mcreator.net/user/469167/shadowdragon019)
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Stone Upgrade
- [ ] Animation Credits [Shadowdragon](https://mcreator.net/user/469167/shadowdragon019)
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Iron Upgrade
- [ ] Animation Credits [Shadowdragon](https://mcreator.net/user/469167/shadowdragon019)
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Golden Upgrade
- [ ] Animation Credits [Shadowdragon](https://mcreator.net/user/469167/shadowdragon019)
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Diamond Upgrade
- [ ] Animation Credits [Shadowdragon](https://mcreator.net/user/469167/shadowdragon019)
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

## Netherite Upgrade
- [ ] Animation Credits [Shadowdragon](https://mcreator.net/user/469167/shadowdragon019)
- [ ] Recipes
- [ ] Textures
- [ ] Wiki Integration
- [ ] Wiki Page

# 🗂 Creative Tab
## Automation
- [ ] Wiki Page

# 🏷 Tag Support
- [ ] Aluminum Block
- [ ] Aluminum Cable
- [ ] Aluminum Ingot
- [ ] Aluminum Ore
- [ ] Auto Farm
- [x] Battery
- [ ] Breaker Panel
- [ ] Cable Bridge
- [x] Diamond Upgrade
- [x] Iron Upgrade
- [x] Golden Upgrade
- [ ] Machine Block
- [ ] Machine Wrench
- [x] Netherite Upgrade
- [ ] Raw Aluminum
- [ ] Raw Aluminum Block
- [ ] Remote Item Teleporter
- [ ] Solar Panel
- [ ] Stone Upgrade
- [x] Wooden Upgrade
- [ ] Recipes
